### ISSUE TITLE
GEO IP not as accurate as ip-api from previous builds

### ISSUE THREAD

**Issue by MathNodes** [sentinel-official/dvpn-node#121]
In reference to https://github.com/sentinel-official/dvpn-node/commit/72f546a0231ec0c39424feaff9fe08aa52761fb6

My node using old ip-api shows current location of Guatemala, now in 0.5.3 shows United states.

Many nodes now do not have a city location. This API is worse than older versions. Please revert back.

**Comment by bsrinivas8687** [comment]
Fixed in #122
