### ISSUE TITLE
Getting error building node version > 0.6.1

### ISSUE THREAD

**Issue by MathNodes** [sentinel-official/dvpn-node#135]
Trying to build anything higher than 0.6.1 spits out the following:

```
Step 3/8 : RUN --mount=target=/go/pkg/mod,type=cache     --mount=target=/root/.cache/go-build,type=cache     apk add autoconf automake bash file g++ gcc git libtool linux-headers make musl-dev unbound-dev &&     cd /root/dvpn-node/ && make --jobs=$(nproc) install &&     git clone --branch=master --depth=1 https://github.com/handshake-org/hnsd.git /root/hnsd &&     cd /root/hnsd/ && bash autogen.sh && sh configure && make --jobs=$(nproc)
the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled
```

**Comment by bsrinivas8687** [comment]
Please update your Docker software to the latest version

**Comment by MathNodes** [comment]
I did that. What was also needed was:

```
mkdir -p $HOME/.docker/cli-plugins && \
cd $HOME/.docker/cli-plugins && \
wget https://github.com/docker/buildx/releases/download/v0.10.4/buildx-v0.10.4.linux-amd64 && \
mv buildx-v0.10.4.linux-amd64 docker-buildx && \
chmod +x docker-buildx
```

**Comment by bsrinivas8687** [comment]
What's the version of Docker software you are using?

`docker version`

**Comment by MathNodes** [comment]
I ran the `get-docker.sh` to update docker:

sentinel@zozobra:~$ docker version
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:46:49 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:49 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.19
  GitCommit:        1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by bsrinivas8687** [comment]
I just tried it on new VM. I am unable to reporduce the issue.

**Comment by MathNodes** [comment]
I was able to install no problem on a new VM as well. But this came from upgrading a node that had 0.4.0 on it and is 4 months old where I needed to upgrade docker. Anyhow, worry not about it. I will close.
