### ISSUE TITLE
ABCI error

### ISSUE THREAD

**Issue by martinholovsky** [sentinel-official/dvpn-node#3]
**Describe the bug**
Clean installation on stable Alpine Linux.

**To Reproduce**

vps:~/.sentinel$ sudo docker run -it --privileged --mount type=bind,source=$HOME/.sentinel,target=/root/.sentinel -p 3000:3000 -p 1194:1194/udp sentinelofficial/stt1-dvpn-
openvpn
[sudo] password for DELETED: 
Unable to find image 'sentinelofficial/stt1-dvpn-openvpn:latest' locally
latest: Pulling from sentinelofficial/stt1-dvpn-openvpn
5d20c808ce19: Already exists 
f612de514f34: Already exists 
b70fd0c1cb84: Already exists 
4cc8806b3258: Already exists 
c50f2da987d6: Already exists 
b3e884298038: Already exists 
a3140d54a9ad: Already exists 
14632061e796: Already exists 
Digest: sha256:71dc5e3ce73ab69b430168dd719c768b6ff2906254a710c7b74424beea81fe99
Status: Downloaded newer image for sentinelofficial/stt1-dvpn-openvpn:latest
I[03-06|06:32:19.367] Starting RPC HTTP server on tcp://localhost:1317 module=rest-server 
I[03-06|06:32:19.384] REST server started                          module=rest-server 

Please enter account name: DELETED
Please enter account password: DELETED

I[03-06|06:32:35.539] Served RPC HTTP response                     module=rest-server method=GET url=/keys/seed status=200 duration=370 remoteAddr=127.0.0.1:49344
I[03-06|06:32:35.826] Served RPC HTTP response                     module=rest-server method=POST url=/keys status=200 duration=283 remoteAddr=127.0.0.1:49346
Updating location and Internet speed information...
No account found.  Returning 0.
No account found, defaulting to sequence 0
I[03-06|06:34:58.366] Served RPC HTTP response                     module=rest-server method=POST url=/register/vpn status=500 duration=724 remoteAddr=127.0.0.1:49550
{'message': '**Response status code is not 200**.', 'code': 2, 'error': 'checkTx failed: (65545) === ABCI Log ===\nCodespace: 1\nCode:      9\nABCICode:  65545\nError:     --= Error =--\nData: common.FmtError{format:"cosmosaccaddrDELETED", args:[]interface {}(nil)}\nMsg Traces:\n--= /Error =--\n\n=== /ABCI Log ===\n'}

**Expected behavior**
dVPN node start

**Screenshots**
console output provided

**Desktop (please complete the following information):**
 - OS: Linux vps 4.19.98-0-virt #1-Alpine SMP Thu Jan 23 11:06:31 UTC 2020 x86_64 Linux
 - Version: latest

**Comment by ironman0x7b2** [comment]
Currently Turing-1 is not running! Will push new updates soon.
