### ISSUE TITLE
Connection time outs

### ISSUE THREAD

**Issue by OrcOrcOrcOrc** [sentinel-official/dvpn-node#43]
**Describe the bug**
When connected to a dvpn node I can not connect to all sites that I want to visit and get a time out on most of them. Same when making a sentinelcli query. I also can't disconnect.

⠀
**Expected behavior**
I should be able to visit every site without any problems

⠀
**Screenshots**
I made a video of me connecting to a node and randomly surfing and running into the error
https://streamable.com/9xxr3w

**0:00-0:30**
connecting to the node

**0:30-3:50**
visiting sites

**3:50-4:40**
error requesting node list with CLI client. 
"error: post failed: Post "https://rpc.sentinel.co:443": read tcp 10.8.0.3:45694->144.126.240.160:443: read: connection reset by peer"

**4:40-5:40**
trying to disconnect
When using sudo command: "sudo: sentinelcli: command not found"
Without sudo it does not disconnect

⠀
**Desktop (please complete the following information):**
OS: Ubuntu 20.04.2 LTS x86_64 
Host: VMware Virtual Platform None 
Kernel: 5.8.0-59-generic 
Uptime: 1 min 
Packages: 2145 (dpkg), 8 (snap) 
Shell: bash 5.0.17 

⠀
**Additional Info**
Sites that worked while testing:
https://whatsmyip.com/
https://www.google.com/search?q=
https://en.wikipedia.org
https://www.apple.com/maps/
https://www.mintscan.io/ (only kinda)
https://www.youtube.com/  (only kinda)

Sites that didn't work while testing:
https://ipleak.net/
https://maps.google.com/
https://maps.me/
https://maps.org/
https://www.davidrumsey.com/
https://www.mapsofworld.com/
https://www.mapbox.com/maps
https://www.cnet.com/
https://www.businessinsider.com/
https://wccftech.com/

**Comment by bsrinivas8687** [comment]
Hi @hoonara I think it's becuase of DNS issues. Are you still facing the issue?

**Comment by bsrinivas8687** [comment]
This is a DNS issue, the DNS servers used by some dVPN nodes are unable to resolve some websites. We are adding a feature to the client, using which user can provide extra optional DNS servers while connecting to a dVPN node.

**Comment by bsrinivas8687** [comment]
@hoonara We have released a version v0.1.8 with flag `--resolver` so you can provider additional trusted DNS servers
