### ISSUE TITLE
CLI Command to Retire a NODE

### ISSUE THREAD

**Issue by HammontreeArt** [sentinel-official/dvpn-node#80]
**Is your feature request related to a problem? Please describe.**
Imagine a node operator needs to shutdown their server, but there is no way to gracefully un-register or de-list the node. 
This will cause dead-nodes to be listed in the Android / iOS client, and cause frustration to the customer. 

**Describe the solution you'd like**
Please provide a CLI command method to de-list or de-register a node.

**Describe alternatives you've considered**
Maybe have a clean up routine running that checks for the client IP.
Maybe you already have a process that does this. 
I can tell from the log that the nodes are checked every 2 min.
So, if a node goes off-line and is dead for x-period of time, then it could be de-listed.

![image](https://user-images.githubusercontent.com/90418397/143071914-3ec44fd1-72fe-4f9f-ab66-dc51a7e9d58e.png)

**Comment by bsrinivas8687** [comment]
Hi @HammontreeArt 

You can just stop the node so it will be removed from the active list within an hour.

**Comment by HammontreeArt** [comment]
Okay, thanks.  That makes sense.    

ANSWER:
A clean-up routine removes or de-lists the node when it's not active.
