### ISSUE TITLE
MEDIUM Article: Multi-Currency Payment for ATOM, UST, OSMO and other IBC (Available only in CLI)

### ISSUE THREAD

**Issue by HammontreeArt** [sentinel-official/dvpn-node#81]
**Is your feature request related to a problem? Please describe.**
I am not able to find the CLI command or instructions to activate Multi-Currency payment for IBC compatible chains.

**Describe the solution you'd like**
Please, where may I find the CLI commands / instructions. 

**Describe alternatives you've considered**
not applicable. 

**Additional context**
Medium Article
https://sentinel.medium.com/the-launch-of-sentinels-first-incentivized-bandwidth-mining-program-on-its-cosmos-based-hub-33e8bcb7bffa

Section of the Article that mentions the CLI commands:
![image](https://user-images.githubusercontent.com/90418397/143071101-aaf1ae52-fd9b-4fbc-8e71-796bae3cf3f0.png)

Discord Mention:
![image](https://user-images.githubusercontent.com/90418397/143071323-34bb816c-8e0d-4a4a-b044-5a3ed71d06fb.png)

**Comment by bsrinivas8687** [comment]
Hi @HammontreeArt You can set the denomination for key price under node secion in config.toml file

**Comment by HammontreeArt** [comment]
Thanks.
