### ISSUE TITLE
Docker LOG shows PEERs connected after disconnecting

### ISSUE THREAD

**Issue by HammontreeArt** [sentinel-official/dvpn-node#82]
**Describe the bug**
The NODE Docker log shows 2 peers connected for 30 min after I disconnected the peers.

**To Reproduce**
Step #1
sentinelcli query node  --home "${HOME}/.sentinelcli"  --node https://rpc.sentinel.co:443 sentnode1...l23z57  
Query results show PEERS = 0.

Step #2 
Used my phone to subscribe to the node and Connected to the node (Moniker:  CherokeeRoseNode )  [in USA]

Step #3 
sentinelcli query node  --home "${HOME}/.sentinelcli"  --node https://rpc.sentinel.co:443 sentnode1...l23z57
Query Results show PEERS = 2

Step #4
On the Android device Disconnect from VPN node. 

Step #5 
Execute docker logs command:     docker logs 28...5e --follow
![image](https://user-images.githubusercontent.com/90418397/143134519-16f50a84-5ab5-4444-9041-7d403dcc2ad0.png)

**Expected behavior**
I was expecting the peers to show zero in the NODE query, but the query showed 2 peers for 40 min and counting. 
sentinelcli query node  --home "${HOME}/.sentinelcli"  --node https://rpc.sentinel.co:443 sentnode1...l23z57
![image](https://user-images.githubusercontent.com/90418397/143134624-535e1269-4b10-48e1-9180-08d77fadebbb.png)

**Screenshots**
tx_hash=CC3B80B82E4A3ACEBF1E858CE5F3CCFF82CBF5B01FBBF5314D67D9D5B804D840
![image](https://user-images.githubusercontent.com/90418397/143133154-c3ee363a-1b20-4fd1-bd97-0ea58bfa18f9.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 20.04 LTS

**Additional context**

**Comment by HammontreeArt** [comment]
Looks like someone did a quick test.   Here is the log.
[20211123_NODE_l23x57_LOG_PEER_TEST.txt](https://github.com/sentinel-official/dvpn-node/files/7591643/20211123_NODE_l23x57_LOG_PEER_TEST.txt)

**Comment by bsrinivas8687** [comment]
Hi @HammontreeArt 

Currently, this is an expected behaviour of the node. The inactive peers will be removed only after updating the pending session information.

**Comment by HammontreeArt** [comment]
Okay, thanks.
