### ISSUE TITLE
v0.3.0 error: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by alexsmith540** [sentinel-official/dvpn-node#96]
**OS:** Ubuntu 20
**dvpn-node version:** 0.3.0
**Description:** 
We have successfully deployed v0.3.0 on 5 of 6 of our testing machines, however on one of the machines we run into the error below no matter what we try. Things we tried: re-building dvpn-node from source multiple times, removing all docker images in case it was somehow cached on an image
I ran it on a clone hardware setup (Ubuntu 20) and everything updated fine, as did Ubuntu 21 machines. We are trying to see if we can pinpoint why this is one in 6 case is occurring before we roll out our HandyHost update.

**Error:**

2022-04-02T05:11:31Z INF Querying session id=46651
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x140c7bc]

goroutine 510 [running]:
github.com/sentinel-official/dvpn-node/node.(*Node).jobUpdateSessions(0xc00128e3f0)
  /go/src/github.com/sentinel-official/dvpn-node/node/jobs.go:109 +0x37c
github.com/sentinel-official/dvpn-node/node.(*Node).Start.func3()
  /go/src/github.com/sentinel-official/dvpn-node/node/node.go:52 +0x1d
created by github.com/sentinel-official/dvpn-node/node.(*Node).Start
  /go/src/github.com/sentinel-official/dvpn-node/node/node.go:51 +0x110

**Comment by wisdomnode** [comment]
cd dvpn-node
rm ~/.sentinelnode/data.db
